# Usar uma imagem base oficial do Node.js
FROM node:18

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o package.json e o package-lock.json
COPY package*.json ./

# Instalar as dependências da aplicação
RUN npm install

# Copiar o restante do código da aplicação
COPY . .

# Expor a porta em que a aplicação irá rodar
EXPOSE 5000

# Definir o comando para iniciar a aplicação
CMD [ "node", "server.js" ]